export const CHANGE_CURRENT_MUSIC_LIST = 'CHANGE_CURRENT_MUSIC_LIST';

export const HIDE_MUSIC_LIST = 'HIDE_MUSIC_LIST';

export const CHANGE_CURRENT_MUSIC = 'CHANGE_CURRENT_MUSIC';

export const CHANGE_PLAYING_STATUS = 'CHANGE_PLAYING_STATUS';

export const CHANGE_PLAY_LIST = 'CHANGE_PLAY_LIST';

export const CHANGE_CURRENT_INDEX = 'CHANGE_CURRENT_INDEX';

export const CHANGE_PLAY_MODE = 'CHANGE_PLAY_MODE';

export const TOGGLE_SHOW_MUSIC_DETAIL = 'TOGGLE_SHOW_MUSIC_DETAIL';

export const CHANGE_CURRENT_MUSIC_LYRIC = 'CHANGE_CURRENT_MUSIC_LYRIC';

export const CHANGE_SINGER_INFO = 'CHANGE_SINGER_INFO';

export const HIDE_SINGER_INFO = 'HIDE_SINGER_INFO';

export const CHANGE_COLLECTOR = 'CHANGE_COLLECTOR';

export const REFRESH_COLLECTOR = 'REFRESH_COLLECTOR';

export const CHANGE_SHOW_LOADING = 'CHANGE_SHOW_LOADING';

export const HIDE_ALL = 'HIDE_ALL';

export const CHANGE_VOLUME = 'CHANGE_VOLUME';

