export const CHANGE_CURRENT_MUSIC_LIST = 'CHANGE_CURRENT_MUSIC_LIST';

export const HIDE_MUSIC_LIST = 'HIDE_MUSIC_LIST';

export const CHANGE_CURRENT_MUSIC = 'CHANGE_CURRENT_MUSIC';

export const CHANGE_PLAYING_STATUS = 'CHANGE_PLAYING_STATUS';

export const CHANGE_PLAY_LIST = 'CHANGE_PLAY_LIST';

export const CHANGE_CURRENT_INDEX = 'CHANGE_CURRENT_INDEX';